{% set version = '2.20.36' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgtk2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RGtk2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RGtk2/RGtk2_{{ version }}.tar.gz
  sha256: d7ff2590dae9e93c185ab2afb1df37fd590332635451f5de863c8a4a271febef

build:
  merge_build_host: True  # [win]
  # GTK2 is not available under win
  skip: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - gtk2
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - gtk2

test:
  commands:
    - $R -e "library('RGtk2')"           # [not win]
    - "\"%R%\" -e \"library('RGtk2')\""  # [win]

about:
  home: http://www.ggobi.org/rgtk2, http://www.omegahat.net
  license: GPL
  summary: Facilities in the R language for programming graphical interfaces using Gtk, the Gimp
    Tool Kit.
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RGtk2
# Version: 2.20.36
# Title: R Bindings for Gtk 2.8.0 and Above
# Author: Michael Lawrence <michafla@gene.com> and Duncan Temple Lang <duncan@wald.ucdavis.edu>
# Depends: R (>= 3.4.0)
# Imports: methods
# SystemRequirements: Cairo (>= 1.0.0), ATK (>= 1.10.0), Pango (>= 1.10.0), GTK+ (>= 2.8.0), GLib (>= 2.8.0)
# Maintainer: Michael Lawrence <michafla@gene.com>
# Description: Facilities in the R language for programming graphical interfaces using Gtk, the Gimp Tool Kit.
# License: GPL
# URL: http://www.ggobi.org/rgtk2, http://www.omegahat.net
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2019-03-03 23:20:52 UTC; larman
# Repository: CRAN
# Date/Publication: 2019-03-08 15:32:41 UTC
